variables:
  ACRRESOURCEGROUP:
    description: "the ACR resource group"
    validation: "azResourceGroup"
  AZURECONTAINERREGISTRY:
    description: "the Azure container registry name"
    validation: "azContainerRegistry"
  CONTAINERNAME:
    description: "the container image name"
    validation: "containerName"
  BUILDCONTEXTPATH:
    description: "the path to the Docker build context"
    validation: "dir"
    value: "."
  BRANCHNAME:
    description: "the Github branch to automatically deploy from"
    validation: "ghBranch"
  CHARTPATH:
    description: "the path to the Helm chart"
    disablePrompt: true
    validation: "dir"
    value: "./charts"
  CHARTOVERRIDEPATH:
    description: "the path to the Helm chart override file"
    disablePrompt: true
    validation: "dir"
    value: "./charts/production.yaml"
  CHARTOVERRIDES:
    description: "the Helm chart overrides"
    disablePrompt: true
    value: "replicas:2"
  CLUSTERNAME:
    description: "the AKS cluster name"
    validation: "azClusterName"
  CLUSTERRESOURCEGROUP:
    description: "the AKS cluster resource group"
    validation: "azResourceGroup"
  DOCKERFILE:
    description: "the path to the Dockerfile"
    validation: "dir"
  NAMESPACE:
    description: "the Kubernetes namespace"
    value: "default"
  PRIVATECLUSTER:
    description: "set to true if the AKS cluster is private"
    type: "bool"
    value: "false"
  WORKFLOWNAME:
    description: "the name of the workflow"
    value: "Build and deploy an app to AKS with Helm"
  

